// Optional in-memory PostgreSQL/WASM validation. Never connects to any server.
// NODE_PATH=<temporary validation dependencies>/node_modules node tests/dashboard-sql.cjs
const {PGlite}=require('@electric-sql/pglite');const fs=require('node:fs'),assert=require('node:assert/strict'),path=require('node:path');
(async()=>{const db=new PGlite();const root=path.resolve(__dirname,'..');const uid='00000000-0000-0000-0000-000000000001',tid='00000000-0000-0000-0000-000000000002';
const query=async sql=>(await db.query(sql)).rows;
const asUser=async(sql,role='authenticated')=>{await db.exec(`set role ${role};set request.jwt.claim.sub='${uid}';`);try{return await query(sql);}finally{await db.exec('reset role;');}};
try{
 await db.exec(`create role anon;create role authenticated;grant usage on schema public to anon,authenticated;create schema auth;create table auth.users(id uuid,raw_app_meta_data jsonb);create function auth.uid() returns uuid language sql as $$ select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;insert into auth.users values ('${uid}','{}');create table public.bridge_tasks(id uuid primary key,instruction text,status text,created_at timestamptz default now(),claimed_at timestamptz,completed_at timestamptz,updated_at timestamptz);alter table public.bridge_tasks enable row level security;insert into public.bridge_tasks(id,instruction,status) values ('${tid}','private instruction','queued');`);
 const migration=fs.readFileSync(path.join(root,'database/dashboard-read.sql'),'utf8');await db.exec(migration);await db.exec(migration);
 assert.equal((await asUser('select public.bridge_dashboard_list() value'))[0].value.length,1);await assert.rejects(()=>asUser('select public.bridge_dashboard_list()','anon'));
 await db.exec(`update auth.users set raw_app_meta_data='{"bridge_dashboard":true}';`);
 let data=(await asUser('select public.bridge_dashboard_list() value'))[0].value;assert.equal(data.length,1);assert.equal(data[0].task_name,'Tarefa sem título');assert.ok(!('instruction' in data[0]));assert.ok(!('recent_output' in data[0]));
 await assert.rejects(()=>asUser('select * from public.bridge_tasks'));await assert.rejects(()=>asUser("update public.bridge_tasks set status='running'"));await assert.rejects(()=>asUser("select public.bridge_dashboard_list(p_status=>'invalid')"));
 await db.exec(`alter table public.bridge_tasks add task_number bigint,add title text,add recent_output text,add progress_seq bigint;update public.bridge_tasks set task_number=12,title='Diagnóstico',progress_seq=9007199254740993,recent_output=E'normal\\nAuthorization: fixture-secret\\nlast';`);
 let detail=(await asUser(`select public.bridge_dashboard_detail('${tid}') value`))[0].value;assert.equal(detail.progress_seq,'9007199254740993');assert.equal(detail.task_number,'12');assert.equal(detail.output_available,false);assert.equal(detail.recent_output,null);
 await db.exec(`update auth.users set raw_app_meta_data='{"bridge_dashboard_logs":true}';`);
 detail=(await asUser(`select public.bridge_dashboard_detail('${tid}') value`))[0].value;assert.ok(detail.output_available);assert.ok(!detail.recent_output.includes('fixture-secret'));assert.ok(detail.recent_output.includes('last'));
 await db.exec(`update public.bridge_tasks set recent_output=repeat(E'line\\n',700);`);detail=(await asUser(`select public.bridge_dashboard_detail('${tid}') value`))[0].value;assert.ok(detail.recent_output.split('\n').length<=500);
 await db.exec(`update public.bridge_tasks set recent_output=repeat(repeat('é',1000)||E'\\n',500);`);detail=(await asUser(`select public.bridge_dashboard_detail('${tid}') value`))[0].value;assert.ok(Buffer.byteLength(JSON.stringify(detail.recent_output))<=524288);
 const stats=(await asUser('select public.bridge_dashboard_stats() value'))[0].value;assert.equal(stats.total,1);assert.equal(stats.counts.queued,1);assert.deepEqual(stats.buckets,[0,0,0,0]);
 const summary=(await asUser(`select public.bridge_dashboard_summary('${tid}') value`))[0].value;assert.ok(!('recent_output' in summary));
 await db.exec(`create schema realtime;create table realtime.messages(payload jsonb);alter table realtime.messages enable row level security;create function realtime.topic() returns text language sql as $$ select 'bridge-dashboard'::text $$;create function realtime.send(jsonb,text,text,boolean) returns void language sql as $$ insert into realtime.messages values($1) $$;`);
 await db.exec(fs.readFileSync(path.join(root,'database/dashboard-authenticated-read.sql'),'utf8'));
 const realtime=fs.readFileSync(path.join(root,'database/dashboard-realtime.sql'),'utf8');await db.exec(realtime);await db.exec(realtime);await db.exec("update public.bridge_tasks set status='running';");const payload=(await query('select payload from realtime.messages limit 1'))[0].payload;assert.deepEqual(Object.keys(payload).sort(),['id','operation','progress_seq']);
 await db.exec(`create or replace function realtime.send(jsonb,text,text,boolean) returns void language plpgsql as $$ begin raise exception 'fixture unavailable'; end $$;update public.bridge_tasks set status='succeeded';`);assert.equal((await query('select status from public.bridge_tasks'))[0].status,'succeeded');
 await db.exec("update auth.users set raw_app_meta_data='{\"bridge_dashboard\":false}';");await assert.rejects(()=>asUser('select public.bridge_dashboard_stats()'));
 await db.exec("alter table auth.users add is_anonymous boolean default false;update auth.users set raw_app_meta_data='{}',is_anonymous=true;");await assert.rejects(()=>asUser('select public.bridge_dashboard_list()'));
 await db.exec("update auth.users set is_anonymous=false;");assert.equal((await asUser('select public.bridge_dashboard_list() value'))[0].value.length,1);
 assert.equal((await query("select relrowsecurity from pg_class where oid='public.bridge_tasks'::regclass"))[0].relrowsecurity,true);
 console.log('Dashboard PostgreSQL/WASM passed: authorization, legacy schema, projection, bigint, redaction gate, bounds, statistics, private broadcast, failure isolation, revocation, idempotence.');
}finally{await db.close();}})().catch(e=>{console.error('Dashboard SQL validation failed:',e.message);process.exitCode=1;});
