'use strict';
const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs'),path=require('node:path'),os=require('node:os'),cp=require('node:child_process');
const core=()=>import('../dashboard/core.mjs');const root=path.resolve(__dirname,'..');
test('dashboard Portuguese states preserve internal lifecycle',async()=>{const m=await core();assert.deepEqual(m.STATES.map(m.statusLabel),['na fila','pausada','em execução','concluída','falhou','cancelada']);assert.equal(m.normalize({id:'internal',status:'running'}).status,'running');});
test('dashboard identity uses number and task_name with legacy fallback',async()=>{const {normalize}=await core();assert.equal(normalize({id:'secret-uuid',task_number:'12',task_name:'Diagnóstico',status:'running'}).summary,'Tarefa 12 — Diagnóstico — em execução');const legacy=normalize({id:'secret-uuid',status:'queued'});assert.ok(!legacy.label.includes('secret-uuid'));assert.equal(normalize({id:'a',title:'Legada',status:'queued'}).task_name,'Legada');});
test('dashboard search supports accent folding, number, state and terminal filtering',async()=>{const {normalize,filterTasks}=await core();const rows=[{id:'a',task_number:1,title:'Diagnóstico',status:'running'},{id:'b',task_number:2,title:'Teste',status:'failed'}].map(normalize);assert.equal(filterTasks(rows,{search:'diagnostico'}).length,1);assert.equal(filterTasks(rows,{search:'2'})[0].id,'b');assert.equal(filterTasks(rows,{status:'queued'}).length,0);assert.equal(filterTasks(rows,{terminal:true})[0].status,'failed');assert.equal(filterTasks(rows,{search:'a',status:'failed'}).length,0);});
test('dashboard handles realtime rows, large progress_seq, and rejects stale sequence',async()=>{const {normalize,mergeTask,hasNewProgress}=await core();const a=normalize({id:'a',status:'running',progress_seq:'9007199254740993'});assert.ok(hasNewProgress(a,{progress_seq:'9007199254740994'}));let rows=mergeTask([a],{...a,progress_seq:'9007199254740994'});assert.equal(rows.length,1);assert.equal(rows[0].progress_seq,'9007199254740994');assert.equal(mergeTask(rows,a),rows);rows=mergeTask(rows,{...rows[0],status:'succeeded'});assert.equal(rows[0].status,'succeeded');const fresh={...rows[0],updated_at:'2026-01-02T00:00:00Z'};assert.equal(mergeTask([fresh],{...fresh,status:'running',updated_at:'2026-01-01T00:00:00Z'})[0].status,'succeeded');});
test('dashboard fallback is 60 seconds only disconnected; reconnect and close clear timer',async()=>{const {Connection}=await core();const pending=new Map();let id=0,reads=0;const states=[];const c=new Connection({refresh:async()=>reads++,timer:(fn,ms)=>{assert.equal(ms,60000);pending.set(++id,fn);return id;},cancel:k=>pending.delete(k),onState:s=>states.push(s)});c.set('connecting');assert.equal(pending.size,1);const f=[...pending.values()][0];await f();assert.equal(reads,1);assert.equal(pending.size,1);c.set('live');assert.equal(pending.size,0);c.set('reconnecting');assert.equal(pending.size,1);c.stop();assert.equal(pending.size,0);c.set('offline');assert.equal(pending.size,0);assert.deepEqual(states,['connecting','connecting','live','reconnecting']);});
test('dashboard limits serialized output, oldest first, escapes executable text',async()=>{const {boundOutput,escape,LIMITS}=await core();assert.equal(LIMITS.lines,500);assert.equal(LIMITS.bytes,524288);assert.equal(LIMITS.flushLines,30);assert.equal(boundOutput(Array.from({length:510},(_,i)=>String(i)).join('\n'))[0],'10');const lines=boundOutput(Array(500).fill('é'.repeat(2000)).join('\n'));assert.ok(Buffer.byteLength(JSON.stringify(lines.join('\n')))<=524288);assert.equal(escape('<img onerror="x">'),'&lt;img onerror=&quot;x&quot;&gt;');});
test('dashboard worker presence is inferred, never false definitive offline',async()=>{const {workerSignal}=await core();assert.equal(workerSignal([]).kind,'unknown');assert.equal(workerSignal([{last_progress_at:new Date().toISOString()}]).kind,'running');});
test('dashboard statistics count English statuses and calculate valid durations',async()=>{const {statistics}=await core();const s=statistics([{status:'succeeded',created_at:'2026-01-01T00:00:00Z',claimed_at:'2026-01-01T00:01:00Z',completed_at:'2026-01-01T00:03:00Z'}]);assert.equal(s.avgWait,60);assert.equal(s.avgDuration,120);assert.equal(s.completionRate,100);assert.equal(s.counts.succeeded,1);assert.deepEqual(s.buckets,[0,1,0,0]);});
test('dashboard config rejects secret/JWT keys and unexpected endpoints',async()=>{const {validateConfig}=await import('../dashboard/data.mjs');for(const publishableKey of ['sb_secret_fixture','eyJfixture','service_role',''])assert.throws(()=>validateConfig({supabaseUrl:'https://example.supabase.co',publishableKey}));for(const supabaseUrl of ['http://example.supabase.co','https://evil.test','https://example.supabase.co/path','https://user@example.supabase.co'])assert.throws(()=>validateConfig({supabaseUrl,publishableKey:'sb_publishable_fixture'}));assert.ok(validateConfig({supabaseUrl:'https://example.supabase.co',publishableKey:'sb_publishable_fixture'}));});
test('dashboard data adapter uses private broadcast and read-only RPC with persistent SDK auth',async()=>{const {createData}=await import('../dashboard/data.mjs');let options,received,liveReceived,subscription,removed=0,signedOut=0;const calls=[];const channel={on(kind,filter,callback){assert.equal(kind,'broadcast');if(filter.event==='task_changed')received=callback;else if(filter.event==='live_activity')liveReceived=callback;else assert.fail('unexpected broadcast');return this;},subscribe(callback){subscription=callback;callback('SUBSCRIBED');return this;}};const client={auth:{onAuthStateChange:()=>({data:{subscription:{unsubscribe(){}}}}),signInWithPassword:async()=>({}),getSession:async()=>({data:{session:{access_token:'fixture-token'}}}),signOut:async()=>{signedOut++;}},rpc:async(name,args)=>{calls.push({name,args});return {data:[]};},realtime:{setAuth:async token=>{assert.equal(token,'fixture-token');}},channel:(topic,opts)=>{assert.equal(topic,'bridge-dashboard');assert.equal(opts.config.private,true);return channel;},removeChannel:()=>removed++};let event,liveEvent;const states=[];const api=await createData({supabaseUrl:'https://example.supabase.co',publishableKey:'sb_publishable_fixture'},{load:async()=>({createClient:(u,k,o)=>{options=o;return client;}}),onEvent:p=>event=p,onLive:p=>liveEvent=p,onState:s=>states.push(s),onRefresh:async()=>{}});await api.login('fixture@example.test','fixture');await api.list({p_limit:50});await api.detail('fixture-id');await api.summary('fixture-id');await api.deleteTask('fixture-id');await api.stats();await api.subscribe();received({payload:{id:'a',progress_seq:'4'}});liveReceived({payload:{id:'a',kind:'output',message:'ok'}});assert.equal(event.progress_seq,'4');assert.equal(liveEvent.message,'ok');subscription('CHANNEL_ERROR');const obsolete=subscription;await api.subscribe();const stateCount=states.length;obsolete('CLOSED');assert.equal(states.length,stateCount);await api.logout();assert.ok(removed>=2);assert.equal(signedOut,1);assert.equal(options.auth.persistSession,true);assert.ok(states.includes('reconnecting'));assert.deepEqual(calls.map(c=>c.name),['bridge_dashboard_list','bridge_dashboard_detail','bridge_dashboard_summary','bridge_dashboard_delete','bridge_dashboard_stats','bridge_dashboard_revision']);});
test('dashboard SQL gates every public read and never grants task table access',()=>{const sql=fs.readFileSync(path.join(root,'database/dashboard-read.sql'),'utf8');assert.equal((sql.match(/if not bridge_dashboard_private.bridge_dashboard_allowed\(\)/g)||[]).length,4);assert.ok(sql.includes('raw_app_meta_data'));assert.ok(!sql.includes('raw_user_meta_data'));assert.ok(sql.includes('p_logs'));assert.ok(!/grant .*on .*bridge_tasks/i.test(sql));assert.ok(!sql.includes("'instruction',"));assert.ok(!sql.includes("'result',"));assert.ok(!sql.includes("'error',"));const rt=fs.readFileSync(path.join(root,'database/dashboard-realtime.sql'),'utf8');assert.ok(rt.includes('realtime.send'));assert.ok(rt.includes('bridge_dashboard_allowed()'));assert.ok(!rt.includes('broadcast_changes'));assert.ok(!rt.includes("'recent_output'"));});
test('dashboard static structure includes accessibility, mobile, CSP, and executive routes',()=>{const html=fs.readFileSync(path.join(root,'dashboard/index.html'),'utf8'),css=fs.readFileSync(path.join(root,'dashboard/styles.css'),'utf8'),app=fs.readFileSync(path.join(root,'dashboard/app.mjs'),'utf8');for(const marker of ['lang="pt-BR"','Content-Security-Policy','aria-label="Navegação principal"','type="module"','<main','<dialog'])assert.ok(html.includes(marker));for(const marker of ['@media(max-width:760px)',':focus-visible','prefers-reduced-motion','td::before'])assert.ok(css.includes(marker));const nav=fs.readFileSync(path.join(root,'dashboard/presentation.mjs'),'utf8');for(const route of ['overview','live','tasks','history','settings'])assert.ok(nav.includes(route+':'));assert.ok(!nav.includes("current:['"));assert.ok(!app.includes('localStorage'));});
test('dashboard build emits only explicit static assets and ignores inherited secrets',()=>{const temp=fs.mkdtempSync(path.join(os.tmpdir(),'bridge-dashboard-'));try{fs.mkdirSync(path.join(temp,'scripts'));fs.cpSync(path.join(root,'dashboard'),path.join(temp,'dashboard'),{recursive:true,filter:p=>!p.includes('/dist')});fs.copyFileSync(path.join(root,'scripts/dashboard-build.cjs'),path.join(temp,'scripts/dashboard-build.cjs'));for(const f of ['task-display.js','task-progress.js'])fs.copyFileSync(path.join(root,f),path.join(temp,f));fs.writeFileSync(path.join(temp,'dashboard/private.key'),'fixture-do-not-copy');const env={PATH:process.env.PATH,CODEX_SUPABASE_SERVICE_ROLE_KEY:'fixture-do-not-copy'};cp.execFileSync(process.execPath,['scripts/dashboard-build.cjs'],{cwd:temp,env});const names=fs.readdirSync(path.join(temp,'dashboard/dist'));assert.equal(names.length,12);assert.ok(!names.includes('private.key'));for(const f of names)assert.ok(!fs.readFileSync(path.join(temp,'dashboard/dist',f),'utf8').includes('fixture-do-not-copy'));const bad=cp.spawnSync(process.execPath,['scripts/dashboard-build.cjs'],{cwd:temp,env:{...env,PUBLIC_SUPABASE_PUBLISHABLE_KEY:'sb_secret_fixture'}});assert.notEqual(bad.status,0);const summary={counts:{queued:0,running:1,succeeded:2,failed:0,cancelled:0},updated_at:'2026-10-04T12:00:00Z'};const summaryFile=path.join(temp,'dashboard/public-summary.json');fs.writeFileSync(summaryFile,JSON.stringify({...summary,secret:'fixture-do-not-copy'}));assert.notEqual(cp.spawnSync(process.execPath,['scripts/dashboard-build.cjs'],{cwd:temp,env:{...env,PUBLIC_DASHBOARD_MODE:'public'}}).status,0);assert.ok(!fs.existsSync(path.join(temp,'dashboard/dist/public-summary.json')));fs.writeFileSync(summaryFile,JSON.stringify(summary));cp.execFileSync(process.execPath,['scripts/dashboard-build.cjs'],{cwd:temp,env:{...env,PUBLIC_DASHBOARD_MODE:'public'}});assert.deepEqual(JSON.parse(fs.readFileSync(path.join(temp,'dashboard/dist/public-summary.json'))),summary);fs.writeFileSync(path.join(temp,'dashboard/dist/private.key'),'fixture-do-not-copy');assert.notEqual(cp.spawnSync(process.execPath,['scripts/dashboard-build.cjs'],{cwd:temp,env}).status,0);assert.ok(fs.existsSync(path.join(temp,'dashboard/dist/private.key')));}finally{fs.rmSync(temp,{recursive:true,force:true});}});

test('live telemetry SQL is ephemeral service-role-only and sanitized',()=>{const sql=fs.readFileSync(path.join(root,'database/dashboard-live.sql'),'utf8');assert.ok(sql.includes("realtime.send(clean,'live_activity','bridge-dashboard',true)"));assert.ok(sql.includes('bridge_dashboard_safe'));assert.ok(sql.includes('grant execute on function public.bridge_dashboard_live_emit(uuid,jsonb) to service_role'));assert.ok(sql.includes('revoke all on function public.bridge_dashboard_live_emit(uuid,jsonb) from public,anon,authenticated'));});

test('dashboard delete flow confirms, cancels, removes and blocks running tasks',async()=>{
 const p=await import('../dashboard/presentation.mjs');
 const label=t=>t.task_number+' — '+t.title;
 const failed={id:'a',task_number:7,title:'Falhou',status:'failed'};
 const running={id:'b',task_number:8,title:'Rodando',status:'running'};
 let prompts=[];
 assert.equal(p.canDeleteTask(failed,'live'),true);
 assert.equal(p.canDeleteTask(running,'live'),false);
 assert.equal(p.confirmTaskDeletion(msg=>{prompts.push(msg);return false;},failed,'live',label),false);
 assert.equal(prompts.length,1);
 assert.match(prompts[0],/7 — Falhou/);
 prompts=[];
 assert.equal(p.confirmTaskDeletion(msg=>{prompts.push(msg);return true;},failed,'live',label),true);
 assert.equal(prompts.length,1);
 prompts=[];
 assert.equal(p.confirmTaskDeletion(msg=>{prompts.push(msg);return true;},running,'live',label),false);
 assert.equal(prompts.length,0);
 assert.deepEqual(p.removeTaskRows([failed,running],'a').map(x=>x.id),['b']);
});

test('dashboard queue pagination uses cursor, filter, search and lookahead row',async()=>{
 const p=await import('../dashboard/presentation.mjs');
 assert.deepEqual(p.queuePageArgs(),{p_limit:13,p_status:null,p_query:null,p_before_created:null,p_before_id:null});
 assert.deepEqual(p.queuePageArgs({status:'failed',search:'teste',cursor:{created_at:'2026-10-06T00:00:00Z',id:'abc'},limit:12}),{p_limit:13,p_status:'failed',p_query:'teste',p_before_created:'2026-10-06T00:00:00Z',p_before_id:'abc'});
 const rows=Array.from({length:13},(_,i)=>({id:String(i),created_at:'2026-10-06T00:00:'+String(i).padStart(2,'0')+'Z'}));
 const page=p.queuePageResult(rows,12);
 assert.equal(page.rows.length,12);assert.equal(page.hasNext,true);assert.equal(page.nextCursor.id,'11');
 const last=p.queuePageResult(rows.slice(0,3),12);assert.equal(last.hasNext,false);assert.equal(last.rows.length,3);
});

test('dashboard build indicator follows current Pages release states',async()=>{
 const {buildReleaseState}=await import('../dashboard/presentation.mjs');
 const base=[{name:'Dashboard Pages',head_sha:'sha1',status:'in_progress',conclusion:null},{name:'Bridge tests',head_sha:'sha1',status:'completed',conclusion:'success'}];
 assert.equal(buildReleaseState(base).status,'running');
 assert.equal(buildReleaseState(base.map(r=>({...r,status:'completed',conclusion:'success'}))).status,'success');
 assert.equal(buildReleaseState([{name:'Dashboard Pages',head_sha:'sha1',status:'completed',conclusion:'success'},{name:'Bridge tests',head_sha:'sha1',status:'completed',conclusion:'failure'}]).status,'failed');
 assert.equal(buildReleaseState([{name:'Dashboard Pages',head_sha:'sha2',status:'completed',conclusion:'success'},{name:'Sync generated docs',head_sha:'sha2',status:'completed',conclusion:'cancelled'}]).status,'success');
 assert.equal(buildReleaseState([]).status,'hidden');
});
