import {normalize,mergeTask,filterTasks,statistics,date,duration,seconds,statusLabel,escape as e} from './core.mjs';
import {taskProgress,taskActivity} from './presentation.mjs';
import {createData,createPublicData} from './data.mjs';

const $=s=>document.querySelector(s), main=$('#main'), nav=$('#nav');
const state={rows:[],stats:null,mode:'offline',route:'overview',search:'',status:'all',connection:'offline',live:[]};
let source=null;
const routes={overview:['Agora','⌁'],live:['Ao vivo','●'],tasks:['Fila','◫'],history:['Prontas','✓'],settings:['Sistema','⚙']};
const copy={queued:'Na fila',running:'Fazendo agora',succeeded:'Pronta',failed:'Precisa de atenção',cancelled:'Cancelada'};
const label=r=>{const name=String(r?.task_name||r?.title||'Tarefa sem título').replace(/^Tarefa\s+\d+\s*[—-]\s*/i,'').trim()||'Tarefa sem título';const number=String(r?.task_number||'').trim();return number?`${number} — ${name}`:(r?.label||name);};
const stats=()=>state.stats||statistics(state.rows);
const current=()=>state.rows.find(r=>r.status==='running');
const queued=()=>state.rows.filter(r=>r.status==='queued').sort((a,b)=>(a.created_at||'').localeCompare(b.created_at||''));
const done=()=>state.rows.filter(r=>['succeeded','failed','cancelled'].includes(r.status)).sort((a,b)=>(b.completed_at||b.updated_at||'').localeCompare(a.completed_at||a.updated_at||''));
const pct=r=>taskProgress(r).value??0;
function ago(v){const t=Date.parse(v||'');if(!Number.isFinite(t))return 'agora';const s=Math.max(0,Math.floor((Date.now()-t)/1000));return s<60?s+'s':s<3600?Math.floor(s/60)+'min':Math.floor(s/3600)+'h';}
function navHtml(){nav.innerHTML=Object.entries(routes).map(([id,x])=>'<a href="#'+id+'" class="'+(state.route===id?'active':'')+'"><span>'+x[1]+'</span>'+x[0]+'</a>').join('');$('#page-title').textContent=routes[state.route]?.[0]||'Agora';}
function flowStep(n,text,done,active=false){return '<div class="flow-step '+(done?'done ':'')+(active?'active':'')+'"><b>'+(done&&!active?'✓':n)+'</b><span>'+text+'</span></div>';}
function hero(){
 const r=current(),q=queued();
 if(!r)return '<section class="hero calm"><div class="hero-orb">✓</div><div><span class="kicker">TUDO TRANQUILO</span><h2>Nada sendo feito agora</h2><p>'+(q.length?q.length+' tarefa'+(q.length>1?'s':'')+' esperando para começar.':'A fila está vazia.')+'</p></div></section>';
 const p=taskProgress(r),a=taskActivity(r,Date.now(),state.connection),n=pct(r);
 return '<section class="hero live" data-running-id="'+e(r.id)+'"><div class="hero-top"><div><span class="live-pill"><i></i> AO VIVO</span><span class="tiny">atualizado há '+e(ago(r.last_progress_at||r.updated_at))+'</span></div><span class="score">⚡ '+n+'%</span></div><div class="hero-copy"><span class="kicker">FAZENDO AGORA</span><h2>'+e(label(r))+'</h2><p>'+e(r.progress_message||p.label||'Trabalhando nesta tarefa.')+'</p></div><div class="mega-progress"><progress aria-label="Progresso da tarefa" max="100" value="'+n+'">'+n+'%</progress><span style="--p:'+n+'%"></span></div><div class="flow">'+flowStep('1','Entrou na fila',true)+flowStep('2','Fazendo',true,true)+flowStep('3','Pronta',false)+'</div><div class="activity-bubble '+a.level+'" data-activity="'+e(r.id)+'"><span class="pulse-dot"></span><strong>'+e(a.text.replace(/^[●!◷○]\s*/,''))+'</strong><small>'+e(a.since)+'</small></div><button class="ghost action" data-task="'+e(r.id)+'">Ver um pouco mais</button></section>';
}
function snapshot(){const s=stats(),q=queued();return '<section class="snapshot"><article><span>▶</span><strong>'+(current()?1:0)+'</strong><small>fazendo agora</small></article><article><span>◷</span><strong>'+q.length+'</strong><small>esperando</small></article><article><span>✓</span><strong>'+(s.counts.succeeded||0)+'</strong><small>prontas</small></article><article><span>✦</span><strong>'+Math.round(s.completionRate||0)+'%</strong><small>de sucesso</small></article></section>';}
function nextUp(){const q=queued().slice(0,4);return '<section class="card"><div class="section-title"><div><span class="kicker">DEPOIS</span><h3>O que vem a seguir</h3></div><span class="count">'+queued().length+'</span></div>'+(q.length?'<div class="queue">'+q.map((r,i)=>'<button data-task="'+e(r.id)+'"><b>'+(i+1)+'</b><span>'+e(label(r))+'<small>esperando para começar</small></span><i>›</i></button>').join('')+'</div>':'<div class="empty-state">Sem tarefas esperando 🎉</div>')+'</section>';}
function wins(){const rows=done().slice(0,5);return '<section class="card"><div class="section-title"><div><span class="kicker">ÚLTIMAS ENTREGAS</span><h3>O que já ficou pronto</h3></div></div><div class="wins-list">'+(rows.length?rows.map(r=>'<button data-task="'+e(r.id)+'"><span class="result-dot '+e(r.status)+'"></span><span>'+e(label(r))+'<small>'+e(copy[r.status]||statusLabel(r.status))+' · '+date(r.completed_at||r.updated_at)+'</small></span><i>'+(r.status==='succeeded'?'✓':'!')+'</i></button>').join(''):'<div class="empty-state">As entregas vão aparecer aqui.</div>')+'</div></section>';}
function overview(){return '<div class="overview">'+hero()+snapshot()+'<div class="split">'+nextUp()+wins()+'</div></div>';}
function livePage(){
 const r=current(),events=r?state.live.filter(x=>x.id===r.id).slice(-120):[],n=r?pct(r):0;
 const stage=events.filter(x=>x.kind==='stage').at(-1)?.message||r?.progress_message||'Executando';
 const lines=events.length?events.map(x=>'<div class="terminal-line '+e(x.kind||'output')+'"><time>'+e(new Date(x.at||Date.now()).toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit',second:'2-digit'}))+'</time><span>'+e(x.message||'')+'</span></div>').join(''):'<div class="terminal-empty">Aguardando novos eventos…</div>';
 return '<section class="live-page"><div class="live-head"><div><span class="live-pill"><i></i> TEMPO REAL</span><h2>'+(r?e(label(r)):'Nenhuma tarefa em execução')+'</h2><p>'+(r?e(r.progress_message||'Acompanhando o Termux em tempo real.'):'Quando uma tarefa começar, ela aparecerá aqui automaticamente.')+'</p></div><div class="live-percent">'+n+'%</div></div>'+(r?'<div class="live-progress"><progress aria-label="Progresso ao vivo" max="100" value="'+n+'"></progress></div><div class="live-stage-grid"><div><span>Etapa atual</span><strong>'+e(stage)+'</strong></div><div><span>Eventos</span><strong>'+events.length+' nesta sessão</strong></div><div><span>Atualização</span><strong>'+e(ago(r.last_progress_at||r.updated_at))+'</strong></div></div><section class="terminal-card"><div class="terminal-top"><div><i></i><span>Termux ao vivo</span></div><small>conteúdo sensível é ocultado</small></div><div id="live-terminal" class="live-terminal" aria-live="polite">'+lines+'</div></section>':'<div class="empty-state big">O painel está conectado e aguardando a próxima execução.</div>')+'</section>';
}
function filters(){return '<div class="filters"><input id="task-search" type="search" value="'+e(state.search)+'" placeholder="Buscar tarefa..."><select id="task-status"><option value="all">Todas</option>'+['queued','running','succeeded','failed','cancelled'].map(x=>'<option value="'+x+'" '+(state.status===x?'selected':'')+'>'+e(copy[x])+'</option>').join('')+'</select></div>';}
function taskRows(history=false){const rows=filterTasks(state.rows,{search:state.search,status:state.status,terminal:history});return rows.length?'<div class="task-grid">'+rows.map(r=>'<button class="task-card '+e(r.status)+'" data-task="'+e(r.id)+'"><span class="task-state">'+e(copy[r.status]||statusLabel(r.status))+'</span><strong>'+e(label(r))+'</strong><div class="mini-bar"><i style="width:'+pct(r)+'%"></i></div><small>'+(r.status==='running'?e(r.progress_message||'em andamento'):date(r.completed_at||r.created_at))+'</small></button>').join('')+'</div>':'<div class="empty-state big">Nada por aqui.</div>';}
function taskPage(history=false){return '<section class="simple-page"><div class="page-intro"><span class="kicker">'+(history?'RESULTADOS':'FLUXO')+'</span><h2>'+(history?'Entregas recentes':'Todas as tarefas')+'</h2></div>'+filters()+'<div id="task-results">'+taskRows(history)+'</div></section>';}
function settings(){return '<section class="simple-page"><div class="page-intro"><span class="kicker">SISTEMA</span><h2>Está tudo conectado?</h2><p>Mostramos apenas o essencial.</p></div><div class="system-card"><div class="system-orb '+e(state.connection)+'"></div><div><strong>'+(state.connection==='live'?'Atualização ao vivo':'Reconectando')+'</strong><small>'+(state.connection==='live'?'Novidades aparecem automaticamente.':'Nenhum dado é exibido até a conexão ser restabelecida.')+'</small></div></div><details class="advanced"><summary>Opções</summary><div class="advanced-body"><button id="pause-follow" aria-pressed="false">Pausar animações</button><input id="log-search" type="search" placeholder="Filtro visual"><p>Login fica salvo neste navegador enquanto a sessão for válida.</p></div></details></section>';}
function render(){navHtml();main.innerHTML=state.route==='overview'?overview():state.route==='live'?livePage():state.route==='tasks'?taskPage(false):state.route==='history'?taskPage(true):settings();bind();$('#updated').textContent='Atualizado '+new Date().toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'});}
function bind(){main.querySelectorAll('[data-task]').forEach(el=>el.onclick=()=>openDetail(el.dataset.task));const s=$('#task-search');if(s)s.oninput=()=>{state.search=s.value;$('#task-results').innerHTML=taskRows(state.route==='history');bind();};const st=$('#task-status');if(st)st.onchange=()=>{state.status=st.value;$('#task-results').innerHTML=taskRows(state.route==='history');bind();};const p=$('#pause-follow');if(p)p.onclick=()=>{const v=p.getAttribute('aria-pressed')==='true';p.setAttribute('aria-pressed',String(!v));document.body.classList.toggle('paused',!v);};}
async function openDetail(id){let r=state.rows.find(x=>x.id===id);if(state.mode==='live'&&source){try{r=normalize(await source.detail(id)||r);}catch{}}if(!r)return;$('#detail-body').innerHTML='<span class="kicker">'+e(copy[r.status]||statusLabel(r.status))+'</span><h2 id="detail-title">'+e(label(r))+'</h2><div class="detail-progress"><progress aria-label="Progresso detalhado" max="100" value="'+pct(r)+'"></progress><strong>'+pct(r)+'%</strong></div><p class="detail-message">'+e(r.progress_message||'Sem mensagem nova.')+'</p><div class="detail-facts"><div><span>Começou</span><strong>'+date(r.claimed_at||r.created_at)+'</strong></div><div><span>Tempo</span><strong>'+duration(seconds(r.claimed_at,r.completed_at||new Date().toISOString()))+'</strong></div></div>';$('#detail-dialog').showModal();}
async function refresh(){if(!source)return;try{if(state.mode==='public')state.stats=await source.stats();else if(state.mode==='live'){const rows=await source.list({p_limit:50,p_offset:0});state.rows=(rows||[]).map(normalize);state.stats=await source.stats();}render();}catch{$('#connection').textContent='Reconectando';}}
async function event(row){state.rows=mergeTask(state.rows,row);if(row?.id&&source&&state.mode==='live'){try{const fresh=await source.summary(row.id);if(fresh)state.rows=mergeTask(state.rows,normalize(fresh));}catch{}}render();}
function liveEvent(payload){if(!payload||typeof payload!=='object'||!payload.id)return;state.live.push(payload);if(state.live.length>500)state.live.splice(0,state.live.length-500);const row=state.rows.find(x=>x.id===payload.id);if(row&&typeof payload.percent==='number')row.progress_percent=payload.percent;if(state.route==='live'){render();requestAnimationFrame(()=>{const box=$('#live-terminal');if(box)box.scrollTop=box.scrollHeight;});}}
async function boot(){render();let config={};try{config=await fetch('./public-config.json',{cache:'no-store'}).then(r=>r.ok?r.json():({}));}catch{}if(config.publicSummaryPath){state.rows=[];state.mode='public';source=createPublicData({config,onRefresh:refresh,onState:s=>{state.connection=s;render();}});state.stats=await source.stats();await source.subscribe();state.connection='live';$('#connection').textContent='Ao vivo';render();return;}if(config.publishableKey){state.rows=[];try{source=await createData(config,{onEvent:event,onLive:liveEvent,onState:s=>{state.connection=s;render();},onRefresh:refresh,onAuthLost:()=>$('#login-dialog').showModal()});if(await source.restore()){state.mode='live';await refresh();await source.subscribe();state.connection='live';$('#connection').textContent='Ao vivo';$('#account').textContent='Conta';$('#notice').hidden=true;return;}state.mode='live';$('#login-dialog').showModal();}catch{$('#login-dialog').showModal();}}else{state.rows=[];state.stats=null;state.mode='offline';state.connection='offline';$('#connection').textContent='Desconectado';$('#notice').hidden=true;render();}}
window.addEventListener('hashchange',()=>{state.route=location.hash.slice(1) in routes?location.hash.slice(1):'overview';render();});
$('#refresh').onclick=refresh;
$('#login-form').onsubmit=async ev=>{ev.preventDefault();const fd=new FormData(ev.currentTarget),err=$('#login-error');err.textContent='';try{await source.login(fd.get('email'),fd.get('password'));$('#login-dialog').close();await refresh();await source.subscribe();state.connection='live';$('#notice').hidden=true;}catch(x){err.textContent=x.message;}};
document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>b.closest('dialog').close());
state.route=location.hash.slice(1) in routes?location.hash.slice(1):'overview';
boot();
setInterval(()=>{if(state.route==='overview')render();},30000);
