import {NAV,STATUS_COPY,progressValue,providerName,providerHealth,stages,quotaLabel} from './presentation.mjs';
import {normalize,mergeTask,filterTasks,statistics,seconds,duration,date,day,escape as e,statusLabel,STATES,REASONS,workerSignal,boundOutput,LIMITS} from './core.mjs';
import {line,bars,donut} from './charts.mjs';
import {demoTasks} from './demo.mjs';
import {createData,createPublicData} from './data.mjs';
const $=s=>document.querySelector(s), main=$('#main');
const routes=NAV;
const state={mode:'demo',rows:demoTasks().map(normalize),stats:null,route:'overview',search:'',status:'all',selected:null,detail:null,tab:'output',auto:true,paused:false,logSearch:'',connection:'demo',updated:Date.now(),busy:false,more:false};
let activeRows=null;
let source=null,epoch=0,eventTimer,statsTimer,searchTimer,request=0,detailRequest=0;
const pendingEvents=new Map();
const chip=r=>{const [icon,label]=STATUS_COPY[r.status]||['○','Aguardando informação'];return `<span class="chip ${e(r.status)}"><span aria-hidden="true">${icon}</span> ${e(label)}</span>`;};
const elapsed=r=>duration(seconds(r.claimed_at,r.completed_at||new Date().toISOString()));
const taskButton=r=>`<button class="task-link" data-task="${e(r.id)}">${e(r.label)}</button>`;
function metadata(r){return `<dl class="metadata"><div><dt>Criada</dt><dd>${date(r.created_at)}</dd></div><div><dt>Início</dt><dd>${date(r.claimed_at)}</dd></div><div><dt>Duração</dt><dd data-elapsed="${e(r.id)}">${elapsed(r)}</dd></div><div><dt>Último progresso</dt><dd>${date(r.last_progress_at)}</dd></div><div><dt>Sequência de progresso</dt><dd>${e(r.progress_seq)}</dd></div><div><dt>Motivo / novas linhas</dt><dd>${e(REASONS[r.last_flush_reason]||'—')} / ${e(r.last_flush_line_count??'—')}</dd></div></dl>`;}
function progress(r){const n=progressValue(r);return `<div class="progress-caption"><strong>${n===null?(r.status==='running'?'Trabalho em andamento':statusLabel(r.status)):n+'% concluído'}</strong><span>${n===null?'Percentual não informado pelo agente':''}</span></div><div class="progress-track ${n===null?'indeterminate':''}" ${n===null?'role="img" aria-label="Progresso sem percentual"':`role="progressbar" aria-label="Progresso da tarefa" aria-valuemin="0" aria-valuemax="100" aria-valuenow="${n}"`}>${n===null?'':`<progress max="100" value="${n}">${n}%</progress>`}</div>`;}
function activeCard(r){if(!r&&state.mode==='public')return `<span class="eyebrow">AGORA</span><h2>${stats().updated_at?Number(stats().counts.running)+' tarefas em execução':'Aguardando indicadores'}</h2><p>A consulta pública protege os nomes e detalhes. Aqui você acompanha apenas os números da operação.</p>`;if(!r)return `<span class="eyebrow">AGORA</span><h2>Tudo pronto para a próxima tarefa</h2><p>${stats().counts.queued?'Há tarefas aguardando. O início da próxima execução ainda não foi confirmado.':'Nenhuma tarefa em execução nos dados disponíveis.'}</p><a class="text-action" href="#tasks">Acompanhar tarefas →</a>`;return `<div class="section-head"><span class="eyebrow">${r.status==='running'?'AGORA · SUA TAREFA EM MOVIMENTO':'RESUMO DA TAREFA'}</span>${chip(r)}</div><h2 class="task-heading">${taskButton(r)}</h2><p class="current-message">${e(r.progress_message||'O agente está trabalhando. Novidades aparecerão aqui.')}</p>${progress(r)}<ol class="steps">${stages(r).map(x=>`<li class="${x.state}"><span aria-hidden="true">${x.state==='done'?'✓':x.state==='current'?'●':'○'}</span>${e(x.label)}<small>${x.state==='done'?'Etapa concluída':x.state==='current'?'Etapa atual':'A seguir'}</small></li>`).join('')}</ol><div class="human-meta"><div><span>Quem está cuidando</span><strong>${e(providerName(r.actual_provider))}</strong><small>${e(r.provider_model||'Modelo não informado')}</small></div><div><span>Tempo decorrido</span><strong data-elapsed="${e(r.id)}">${elapsed(r)}</strong></div><div><span>Última atualização</span><strong>${date(r.last_progress_at||r.updated_at)}</strong></div><div><span>Cota do agente</span><strong>${e(quotaLabel(r))}</strong></div></div><button class="primary" data-task="${e(r.id)}">Acompanhar detalhes →</button>`;}
function providers(){return `<section class="card provider-card"><div class="section-head"><div><span class="eyebrow">EQUIPE DIGITAL</span><h2>Saúde dos agentes</h2></div><a href="#settings">Ver sistema →</a></div><div class="provider-grid">${['codex','groq','antigravity','claude','local'].map(id=>{const item=(state.stats?.providers||(state.mode==='demo'?[{provider:'groq',state:'ready'},{provider:'codex',state:'ready'}]:[])).find(p=>p.provider===id);const [icon,label]=providerHealth(item?.state);return `<div class="provider-item"><span class="provider-avatar" aria-hidden="true">${providerName(id).slice(0,1)}</span><div><strong>${e(providerName(id))}</strong><small>${icon} ${e(label)}</small></div></div>`;}).join('')}</div><p class="subtle">Sem informação não significa indisponível. A conexão é confirmada quando há uma verificação do agente.</p></section>`;}

function current(){return (activeRows||state.rows).find(r=>r.status==='running');}
function stats(){return state.stats||statistics(state.rows);}
function kpis(){const s=stats();return `<div class="kpis">${[['running','Em execução'],['queued','Na fila'],['succeeded','Concluídas'],['failed','Falhas']].map(([key,label])=>`<article class="kpi ${key}"><span>${label}</span><strong>${state.mode==='public'&&!s.updated_at?'—':Number(s.counts[key]||0)}</strong><small>${key==='running'?'Acompanhamento ao vivo':key==='queued'?'Aguardando o executor':'Na janela de 30 dias'}</small></article>`).join('')}</div>`;}
function timeline(rows){return `<ul class="activity">${rows.map(r=>`<li>${taskButton(r)}<span class="subtle">${e(statusLabel(r.status))} · ${date(r.updated_at||r.completed_at||r.claimed_at||r.created_at)}</span></li>`).join('')}</ul>`;}
function overview(){const s=stats(),r=current(),next=state.rows.filter(t=>t.status==='queued').sort((a,b)=>a.created_at.localeCompare(b.created_at)).slice(0,3);return `<section class="welcome"><div><span class="eyebrow">CLAREZA PARA SEGUIR EM FRENTE</span><h2>Seu trabalho, em movimento.</h2><p>Veja o que acontece agora e o que vem depois.</p></div><span class="health-pill">${s.counts.failed?'! Precisa de atenção':state.mode==='demo'?'◈ Explore a demonstração':'○ Acompanhando a fila'}</span></section>${kpis()}<div class="executive-grid"><section class="card current-hero">${activeCard(r)}</section><section class="card next-card"><span class="eyebrow">PRÓXIMOS PASSOS</span><h2>O que vem depois</h2><p>A ordem mostrada considera a criação das tarefas carregadas.</p>${next.length?`<ol class="next-list">${next.map((t,i)=>`<li><span class="queue-order">${i+1}</span><div>${taskButton(t)}<small>◷ Aguardando início</small></div></li>`).join('')}</ol>`:'<p class="empty">Nenhuma tarefa aguardando nos dados disponíveis.</p>'}<a href="#tasks">Ver toda a fila →</a></section></div>${providers()}<div class="grid equal"><section class="card"><div class="section-head"><h2>O que aconteceu</h2><a href="#history">Ver histórico →</a></div>${timeline([...state.rows].sort((a,b)=>(b.updated_at||b.created_at).localeCompare(a.updated_at||a.created_at)).slice(0,4))}</section><section class="card"><span class="eyebrow">AVANÇO COM PROPÓSITO</span><h2>${s.counts.succeeded?'✓ '+s.counts.succeeded+' entregas concluídas':'Cada conclusão conta'}</h2><p>${s.counts.succeeded?'Trabalho finalizado na janela de 30 dias. Consulte o histórico para ver cada resultado.':'Os marcos aparecerão conforme as tarefas forem concluídas.'}</p><div class="milestone"><strong>${s.completionRate.toFixed(0)}%</strong><span>de sucesso entre tarefas finalizadas</span></div>${line(s.days)}<span class="subtle">Ritmo de entrada · tarefas por dia</span></section></div>`;}

function filters(){return `<div class="filters"><label class="screen-reader" for="task-search">Buscar por número ou nome</label><input id="task-search" type="search" placeholder="Buscar por número ou nome…" value="${e(state.search)}"><label class="screen-reader" for="task-status">Estado da tarefa</label><select id="task-status"><option value="all">Todos os estados</option>${STATES.map(s=>`<option value="${s}" ${state.status===s?'selected':''}>${e(statusLabel(s))}</option>`).join('')}</select></div>`;}
function rowsForPage(){return filterTasks(state.rows,{search:state.search,status:state.status,terminal:state.route==='history'});}
function pagination(){return `<div class="footer-controls"><span>${rowsForPage().length} tarefas carregadas${state.mode==='live'?' · paginação de 50 registros':''}</span>${state.more?'<button data-more>Carregar anteriores</button>':'<span>Fim dos registros carregados</span>'}</div>`;}
function taskTable(){const rows=rowsForPage();return rows.length?`<div class="table-wrap"><table><thead><tr>${['Número','Tarefa','Estado','Progresso','Criada','Início','Conclusão','Duração'].map(x=>`<th scope="col">${x}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr><td data-label="Número" class="number">${r.task_number?'#'+e(r.task_number):'Legada'}</td><td data-label="Tarefa" class="name">${taskButton(r)}</td><td data-label="Estado">${chip(r)}</td><td data-label="Progresso"><span class="table-progress">${progressValue(r)===null?'Em acompanhamento':progressValue(r)+'%'}</span></td><td data-label="Criada">${date(r.created_at)}</td><td data-label="Início">${date(r.claimed_at)}</td><td data-label="Conclusão">${date(r.completed_at)}</td><td data-label="Duração">${elapsed(r)}</td></tr>`).join('')}</tbody></table></div>`:`<div class="empty">${state.mode==='public'?'A consulta pública mostra apenas indicadores. Os nomes e detalhes das tarefas permanecem privados.':'Nenhuma tarefa encontrada. Ajuste os filtros ou atualize os dados.'}</div>`;}
function historyList(){const groups=new Map();for(const r of rowsForPage()){const key=day(r.completed_at||r.created_at);if(!groups.has(key))groups.set(key,[]);groups.get(key).push(r);}return groups.size?[...groups].map(([d,rows])=>`<section class="timeline-group"><h3>${e(d)}</h3>${rows.map(r=>`<div class="timeline-item"><div>${taskButton(r)}<p>${date(r.completed_at||r.created_at)} · duração ${elapsed(r)}</p></div>${chip(r)}</div>`).join('')}</section>`).join(''):'<div class="empty">Nenhuma tarefa finalizada nesta seleção.</div>';}
function tasksPage(history=false){return `<section class="card"><div class="section-head"><h2>${history?'Linha do tempo':'Todas as tarefas'}</h2><span class="subtle">Identidade estável, leitura simples</span></div>${filters()}<div id="task-results">${history?historyList():taskTable()}${pagination()}</div></section>`;}
function outputLines(r){if(!r?.output_available)return '<div class="empty">Saída indisponível. O administrador precisa habilitar a leitura de logs sanitizados.</div>';return boundOutput(r.recent_output).map((text,i)=>({text,i})).filter(({text})=>text.toLocaleLowerCase().includes(state.logSearch.toLocaleLowerCase())).map(({text,i})=>`<div class="line"><b aria-hidden="true">${i+1}</b><code>${e(text)||' '}</code></div>`).join('')||'<div class="empty">Nenhuma linha nesta seleção.</div>';}
function terminal(r){return `<div class="terminal-toolbar"><label><input id="auto-scroll" type="checkbox" ${state.auto?'checked':''}> Rolagem automática</label><button id="pause-follow" aria-pressed="${state.paused}">${state.paused?'Retomar acompanhamento':'Pausar acompanhamento'}</button><label class="screen-reader" for="log-search">Filtrar saída carregada</label><input id="log-search" type="search" placeholder="Buscar nesta saída…" value="${e(state.logSearch)}"></div><div class="terminal" id="terminal" tabindex="0" aria-label="Saída recente sanitizada">${outputLines(r)}</div><p class="terminal-info">Janela recente, não histórico completo: até ${LIMITS.lines} linhas / ${LIMITS.bytes/1024} KiB. ${state.paused?'Acompanhamento pausado; dados continuam chegando.':'Atualizada a cada lote persistido.'}</p>`;}
function currentPage(){const r=state.detail?.id===current()?.id?state.detail:current();if(!r)return '<section class="card"><div class="banner-icon">✓</div><h2>Nenhuma execução ativa</h2><p>A fila está pronta para receber a próxima tarefa. As atualizações aparecerão aqui.</p></section>';return `<section class="card full" data-running-id="${e(r.id)}">${activeCard(r)}</section><section class="card"><div class="tabs" role="group" aria-label="Detalhes da execução">${[['output','Saída em tempo real'],['info','Informações'],['files','Arquivos'],['commands','Comandos']].map(([id,label])=>`<button data-tab="${id}" aria-pressed="${state.tab===id}">${label}</button>`).join('')}</div>${state.tab==='output'?terminal(r):state.tab==='info'?`${metadata(r)}<p>O Codex é o executor. Esta interface apenas observa a fila e não altera tarefas.</p>`:`<div class="empty">${state.tab==='files'?'A ponte não publica um inventário de arquivos. Os logs completos permanecem no Termux.':'A ponte publica o motivo “Comando finalizado”, mas ainda não oferece uma lista estruturada de comandos. Consulte a saída sanitizada.'}</div>`}</section>`;}
function statsPage(){const s=stats();return `${kpis()}<section class="card full"><h2>Qualidade e tempo · últimos 30 dias</h2>${[['Total',s.total],['Canceladas',s.counts.cancelled],['Taxa de sucesso',s.completionRate.toFixed(1)+'%'],['Espera média',duration(s.avgWait)],['Execução média',duration(s.avgDuration)]].map(([k,v])=>`<div class="stat-row"><span>${k}</span><strong>${e(v)}</strong></div>`).join('')}</section><div class="grid equal"><section class="card"><h2>Tarefas criadas por dia</h2>${line(s.days)}</section><section class="card"><h2>Distribuição de estados</h2>${donut(s.counts)}</section><section class="card"><h2>Distribuição de duração</h2>${bars(s.buckets,['< 1 min','1–5 min','5–15 min','≥ 15 min'],'Duração das tarefas finalizadas')}</section><section class="card"><h2>Vazão · finalizadas por dia</h2>${line(s.throughput||throughput(state.rows),"Tarefas finalizadas por dia")}</section></div><section class="card"><h2>Nomes mais frequentes</h2>${s.names.map(([name,n])=>`<div class="stat-row"><span>${e(name)}</span><strong>${Number(n)}</strong></div>`).join('')||'<p>Sem dados suficientes.</p>'}</section>`;}
function throughput(rows){const days=new Map();for(const r of rows){if(r.completed_at){const d=r.completed_at.slice(0,10);days.set(d,(days.get(d)||0)+1);}}return [...days].sort().map(([day,count])=>({day,count}));}
function logsPage(){const r=state.detail?.id===state.selected?state.detail:state.rows.find(r=>r.id===state.selected)||state.rows[0];return `<section class="card"><div class="section-head"><h2>Explorador de saída</h2><span class="subtle">Somente o buffer carregado</span></div><label for="log-task" class="subtle">Selecionar tarefa</label><div class="filters"><select id="log-task">${state.rows.map(row=>`<option value="${e(row.id)}" ${row.id===r?.id?'selected':''}>${e(row.label)}</option>`).join('')}</select></div>${r?`${chip(r)}${metadata(r)}${terminal(r)}`:'<div class="empty">Nenhuma tarefa disponível.</div>'}</section>`;}
function settings(){const w=workerSignal(state.rows);return `<div class="grid equal"><section class="card"><h2>Observabilidade da ponte</h2>${[['Lote de saída',LIMITS.flushLines+' novas linhas OU '+LIMITS.intervalMs/1000+' segundos'],['Conclusão de comando','Flush imediato com linhas pendentes'],['Janela circular',LIMITS.lines+' linhas / '+LIMITS.bytes/1024+' KiB'],['Finalização','Sucesso, falha, cancelamento e shutdown'],['Contador','progress_seq incrementa por flush confirmado'],['Histórico completo','Arquivo privado por tarefa no Termux']].map(([k,v])=>`<div class="stat-row"><span>${k}</span><strong>${e(v)}</strong></div>`).join('')}<p>Valores gerados do código da ponte. O tempo é contado desde o último flush bem-sucedido.</p></section><section class="card"><h2>Conectividade e acesso</h2>${[['Modo',state.mode==='demo'?'Demonstração · dados fictícios':state.mode==='public'?'Público · indicadores agregados':'Conta autenticada'],['Canal Realtime',connectionLabel(state.connection)],['Última leitura',date(state.updated)],['Worker',w.label],['Fallback de leitura','60 s, apenas sem Realtime'],['Permissões',state.mode==='public'?'Somente leitura · indicadores públicos':'Somente leitura · conta autorizada']].map(([k,v])=>`<div class="stat-row"><span>${k}</span><strong>${e(v)}</strong></div>`).join('')}<p>${e(w.detail)}</p><p>Instruções e respostas completas não são publicadas no painel. Logs exigem uma autorização adicional do administrador.</p><button id="reconnect">Reconectar / verificar leitura</button></section></div><section class="card"><h2>Como a fila funciona</h2><p>Você pede algo ao ChatGPT, Gemini ou Claude. A tarefa entra na fila Supabase. O celular com Termux recebe e o Codex executa. O resultado volta à fila para a IA consultar. Este painel acompanha esse caminho; ele não executa comandos.</p><p><a href="https://github.com/AmaroPSJunior/codex-bridge-queue/blob/main/docs/DASHBOARD.md" target="_blank" rel="noreferrer">Instalação, segurança e operação ↗</a></p></section>`;}
function systemPage(){return `<section class="card"><span class="eyebrow">SISTEMA</span><h2>${state.connection==='live'?'✓ Tudo certo com a conexão':state.mode==='demo'?'Explore com tranquilidade':'○ Aguardando conexão'}</h2><p>${state.mode==='demo'?'Você está vendo dados fictícios. Conecte uma conta autorizada para acompanhar sua operação.':'Este painel é somente leitura. Reinícios e outras ações sensíveis permanecem protegidos no backend.'}</p><button id="reconnect">Verificar conexão</button></section>${providers()}<details class="card advanced"><summary>Avançado · conexão, métricas e saída técnica</summary>${settings()}${statsPage()}${logsPage()}</details>`;}
function connectionLabel(s){return ({public:'Consulta pública · a cada minuto',demo:'Demonstração',live:'● Atualizado ao vivo',connecting:'Conectando…',reconnecting:'Reconectando…',offline:'Sem conexão · tente atualizar'})[s]||'Desconectado';}
function chrome(){ $('#account').hidden=state.mode==='public'; $('#connection').textContent=connectionLabel(state.connection);$('#connection').className='chip '+(state.connection==='live'?'succeeded':'queued');$('#account').textContent=state.mode==='demo'?'Conectar':'Sair';$('#updated').textContent='Última leitura: '+date(state.updated); }
function render(){const advancedOpen=Boolean($('.advanced')?.open);const route=location.hash.slice(1);state.route=routes[route]?route:({current:'overview',stats:'settings',logs:'settings'}[route]||'overview');$('#page-title').textContent=routes[state.route][0];$('#nav').innerHTML=Object.entries(routes).map(([id,[label,icon]])=>`<a href="#${id}" ${id===state.route?'aria-current="page"':''}><span class="icon" aria-hidden="true">${icon}</span>${label}</a>`).join('');main.innerHTML=({overview,tasks:()=>tasksPage(),current:currentPage,history:()=>tasksPage(true),stats:statsPage,logs:logsPage,settings:systemPage})[state.route]();if(advancedOpen&&$('.advanced'))$('.advanced').open=true;chrome();scrollOutput();}
function scrollOutput(){const t=$('#terminal');if(t&&state.auto&&!state.paused)t.scrollTop=t.scrollHeight;}
function notice(text,error=false){$('#notice').textContent=text;$('#notice').className='notice'+(error?' error':'');}
function refreshView(){if(['tasks','history'].includes(state.route)&&$('#task-results')){$('#task-results').innerHTML=(state.route==='history'?historyList():taskTable())+pagination();chrome();}else if(['logs','current','settings'].includes(state.route)&&$('#terminal')&&(state.route!=='current'||$('[data-running-id]')?.dataset.runningId===current()?.id)){const r=state.detail||current();if(state.route==='current'&&$('[data-running-id]'))$('[data-running-id]').innerHTML=activeCard(r);if(!state.paused){const t=$('#terminal'),top=t.scrollTop;t.innerHTML=outputLines(r);if(!state.auto)t.scrollTop=top;scrollOutput();}document.querySelectorAll('.metadata').forEach(el=>{const host=document.createElement('div');host.innerHTML=metadata(r||{});el.replaceWith(host.firstElementChild);});chrome();}else if(state.route==='overview'){main.innerHTML=overview();chrome();}else render();}
async function loadDetail(id,{dialog=false}={}){if(!id)return;const generation=epoch,n=++detailRequest;state.selected=id;if(dialog){$('#detail-body').innerHTML='<h2 id="detail-title">Carregando tarefa…</h2>';$('#detail-dialog').showModal();}try{const row=source?await source.detail(id):state.rows.find(r=>r.id===id);if(generation!==epoch||n!==detailRequest)return;if(!row)throw Error('Tarefa indisponível.');state.detail=normalize(row);if(dialog){const r=state.detail;$('#detail-body').innerHTML=`<h2 id="detail-title">${e(r.label)}</h2>${activeCard(r).replace(/<button class="primary"[^>]*>.*?<\/button>/,'')}<p>${e(r.progress_message||'Sem atualização de progresso.')}</p><p>${e(r.result_summary||'Resultado completo disponível na integração autorizada.')}</p><details><summary>Avançado · informações técnicas e saída</summary>${metadata(r)}<div class="terminal" tabindex="0">${outputLines(r)}</div><p>Identificador para suporte</p><code>${e(r.id)}</code></details>`;}else refreshView();}catch(err){if(generation!==epoch)return;if(dialog)$('#detail-body').innerHTML='<h2 id="detail-title">Leitura indisponível</h2><p>Não foi possível abrir esta tarefa.</p>';else notice('Falha ao ler detalhes. Tente atualizar.',true);}}
function listArgs(more){const tail=state.rows.at(-1);return {p_limit:50,p_status:state.status==='all'?null:state.status,p_query:state.search||null,...(more&&tail?{p_before_created:tail.created_at,p_before_id:tail.id}:{})};}
async function refresh(more=false){if(!source){state.updated=Date.now();refreshView();return;}const generation=epoch,n=++request;state.busy=true;$('#refresh').disabled=true;try{const scoped=['tasks','history'].includes(state.route);const [rows,summary,active]=await Promise.all([source.list(scoped?listArgs(more):{p_limit:50}),source.stats(),source.list({p_limit:50,p_status:'running'})]);if(generation!==epoch||n!==request)return;state.rows=more?[...state.rows,...rows.map(normalize).filter(r=>!state.rows.some(x=>x.id===r.id))]:rows.map(normalize);activeRows=active.map(normalize);state.more=rows.length===50;state.stats=summary;state.updated=Date.now();notice(state.mode==='public'?'Consulta pública · somente indicadores agregados · atualizado na origem: '+date(state.stats.updated_at):'Tudo atualizado · consulta segura, sem alterar suas tarefas.');refreshView();const id=state.route==='current'?current()?.id:state.route==='logs'?(state.selected||state.rows[0]?.id):null;if(id)await loadDetail(id);}catch(err){if(generation===epoch&&n===request)notice('Não foi possível atualizar. Os últimos dados continuam visíveis. Confira a conexão ou reconecte.',true);}finally{if(generation===epoch&&n===request){state.busy=false;$('#refresh').disabled=false;}}}
function onEvent(payload){
 if(!source||!payload||typeof payload.id!=='string')return;
 pendingEvents.set(payload.id,payload);
 if(eventTimer)return;
 eventTimer=setTimeout(async()=>{
  eventTimer=null;const generation=epoch,api=source,events=[...pendingEvents.values()];pendingEvents.clear();
  if(!api)return;
  if(events.length>10){await refresh();return;}
  try{
   const changes=await Promise.all(events.map(p=>api.summary(p.id)));
   if(generation!==epoch)return;
   for(let i=0;i<changes.length;i++){
    const row=changes[i],id=events[i].id;
    if(row){const previous=state.rows.find(r=>r.id===row.id);if(previous&&previous.status!=='succeeded'&&row.status==='succeeded'){const feedback=$('#feedback');feedback.textContent='✓ Mais uma entrega concluída. Veja o resultado no Histórico.';feedback.hidden=false;}state.rows=mergeTask(state.rows,row).slice(0,Math.max(50,state.rows.length));activeRows=mergeTask(activeRows||[],row).filter(r=>r.status==='running');}
    else{state.rows=state.rows.filter(r=>r.id!==id);activeRows=(activeRows||[]).filter(r=>r.id!==id);}
   }
   state.updated=Date.now();refreshView();
   const selected=state.route==='current'?current()?.id:state.route==='logs'?(state.selected||state.rows[0]?.id):null;
   if(selected&&events.some(p=>p.id===selected))await loadDetail(selected);
   // Aggregate reads are event-driven and coalesced; never a polling loop.
   if(!statsTimer)statsTimer=setTimeout(async()=>{statsTimer=null;try{const value=await api.stats();if(generation===epoch){state.stats=value;if(['overview','stats'].includes(state.route))refreshView();}}catch{}},15000);
  }catch{if(generation===epoch)notice('Aviso recebido, mas a leitura falhou. Use Atualizar para tentar novamente.',true);}
 },1000);
}
async function disconnect(){epoch++;request++;detailRequest++;clearTimeout(eventTimer);eventTimer=null;clearTimeout(statsTimer);statsTimer=null;pendingEvents.clear();clearTimeout(searchTimer);activeRows=null;$('#refresh').disabled=false;const old=source;source=null;state.mode='demo';state.connection='demo';$('#feedback').hidden=true;state.rows=demoTasks().map(normalize);state.stats=null;state.detail=null;state.selected=null;state.search='';state.status='all';state.more=false;$('#detail-dialog').close();notice('Demonstração • dados fictícios para explorar o painel.');render();if(old)await old.close().catch(()=>{});}
$('#login-form').addEventListener('submit',async event=>{event.preventDefault();const form=event.currentTarget,button=form.querySelector('button');button.disabled=true;$('#login-error').textContent='Conectando…';let candidate;try{const config=await fetch('./public-config.json',{cache:'no-store'}).then(r=>{if(!r.ok)throw Error('Configuração indisponível.');return r.json();});candidate=await createData(config,{onEvent,onState:s=>{state.connection=s;chrome();},onRefresh:()=>refresh(),onAuthLost:()=>{if(source)disconnect();}});const password=form.elements.password.value;form.elements.password.value='';await candidate.login(form.elements.email.value,password);epoch++;source=candidate;state.mode='live';state.rows=[];state.detail=null;state.stats=null;activeRows=[];$('#login-dialog').close();render();notice('Carregando dados autorizados…');await refresh();await source.subscribe();}catch(err){$('#login-error').textContent=err.message||'Conexão indisponível.';if(candidate&&candidate!==source)await candidate.close().catch(()=>{});if(source)notice('Realtime indisponível. Use reconectar ou atualização manual.',true);}finally{button.disabled=false;form.elements.password.value='';}});
$('#account').onclick=()=>state.mode==='live'?disconnect():$('#login-dialog').showModal();$('#refresh').onclick=()=>refresh();
document.addEventListener('click',event=>{const b=event.target.closest('button');if(!b)return;if(b.hasAttribute('data-close'))b.closest('dialog').close();if(b.dataset.task)loadDetail(b.dataset.task,{dialog:true});if(b.dataset.tab){state.tab=b.dataset.tab;render();if(state.tab==='output')loadDetail(current()?.id);}if(b.hasAttribute('data-more'))refresh(true);if(b.id==='pause-follow'){state.paused=!state.paused;b.textContent=state.paused?'Retomar acompanhamento':'Pausar acompanhamento';b.setAttribute('aria-pressed',String(state.paused));if(!state.paused)refreshView();}if(b.id==='reconnect'){if(source){source.subscribe().catch(()=>notice('Não foi possível reconectar.',true));refresh();}else if(state.mode!=='public')$('#login-dialog').showModal();}});
document.addEventListener('input',event=>{if(event.target.id==='task-search'){state.search=event.target.value;if(source){clearTimeout(searchTimer);searchTimer=setTimeout(()=>refresh(),350);}else refreshView();}if(event.target.id==='log-search'){state.logSearch=event.target.value;refreshView();}});
document.addEventListener('change',event=>{if(event.target.id==='task-status'){state.status=event.target.value;source?refresh():refreshView();}if(event.target.id==='auto-scroll'){state.auto=event.target.checked;scrollOutput();}if(event.target.id==='log-task'){state.paused=false;loadDetail(event.target.value);}});
window.addEventListener('hashchange',()=>{detailRequest++;clearTimeout(searchTimer);state.search='';state.status='all';state.detail=null;state.paused=false;render();if(source)refresh();else if(state.route==='current')loadDetail(current()?.id);else if(state.route==='logs')loadDetail(state.selected||state.rows[0]?.id);});
window.addEventListener('online',()=>{if(source){source.subscribe().catch(()=>{});refresh();}});
setInterval(()=>{document.querySelectorAll('[data-elapsed]').forEach(node=>{const r=[...state.rows,...(activeRows||[])].find(r=>r.id===node.dataset.elapsed);if(r)node.textContent=elapsed(r);});},1000);
render();

async function initializePublic(){try{const response=await fetch('./public-config.json',{cache:'no-store'});if(!response.ok)return;const config=await response.json();if(config.publicSummaryPath!=='./public-summary.json')return;epoch++;source=createPublicData({onRefresh:()=>refresh(),onState:s=>{state.connection=s;chrome();}});state.mode='public';state.connection='public';state.rows=[];state.stats=statistics([]);activeRows=[];render();notice('Carregando indicadores públicos…');await refresh();await source.subscribe();}catch{ /* Unconfigured demo stays offline; public errors remain visible. */ }}
void initializePublic();
