import {normalize,mergeTask,applyTaskChange,filterTasks,statistics,date,duration,seconds,statusLabel,escape as e} from './core.mjs';
import {taskProgress,taskActivity,canDeleteTask,confirmTaskDeletion,removeTaskRows,queuePageArgs,queuePageResult,buildReleaseState} from './presentation.mjs';
import {createData,createPublicData} from './data.mjs';

const $=s=>document.querySelector(s), main=$('#main'), nav=$('#nav');
const state={rows:[],stats:null,projects:[],mode:'offline',route:'overview',search:'',status:'all',connection:'offline',live:[],page:{number:1,rows:null,cursors:[null],hasNext:false,loading:false},build:{status:'hidden',sha:null,visibleUntil:0}};
let source=null;
const routes={overview:['Agora','⌁'],live:['Ao vivo','●'],tasks:['Fila','◫'],history:['Prontas','✓'],projects:['Projetos','◆'],settings:['Sistema','⚙']};
const copy={queued:'Na fila',paused:'Pausada',running:'Fazendo agora',succeeded:'Pronta',failed:'Precisa de atenção',cancelled:'Cancelada'};
const label=r=>{const clean=v=>String(v||'').replace(/^Tarefa\s+(?:\d+\s*[—-]\s*)?/i,'').trim();const name=clean(r?.task_name||r?.title)||'Sem título';const number=String(r?.task_number||'').trim();if(number)return `${number} — ${name}`;return clean(r?.label)||name;};
const stats=()=>state.stats||statistics(state.rows);
const current=()=>state.rows.find(r=>r.status==='running');
const queued=()=>state.rows.filter(r=>r.status==='queued').sort((a,b)=>(a.created_at||'').localeCompare(b.created_at||''));
const paused=()=>state.rows.filter(r=>r.status==='paused').sort((a,b)=>(a.created_at||'').localeCompare(b.created_at||''));
const pending=()=>[...queued(),...paused()];
const done=()=>state.rows.filter(r=>['succeeded','failed','cancelled'].includes(r.status)).sort((a,b)=>(b.completed_at||b.updated_at||'').localeCompare(a.completed_at||a.updated_at||''));
const progressValue=r=>taskProgress(r).value;const pct=r=>progressValue(r)??0;const pctText=r=>progressValue(r)===null?'—':progressValue(r)+'%';
function ago(v){const t=Date.parse(v||'');if(!Number.isFinite(t))return 'agora';const s=Math.max(0,Math.floor((Date.now()-t)/1000));return s<60?s+'s':s<3600?Math.floor(s/60)+'min':Math.floor(s/3600)+'h';}
function navHtml(){nav.innerHTML=Object.entries(routes).map(([id,x])=>'<a href="#'+id+'" class="'+(state.route===id?'active':'')+'"><span>'+x[1]+'</span>'+x[0]+'</a>').join('');$('#page-title').textContent=routes[state.route]?.[0]||'Agora';}
function flowStep(n,text,done,active=false){return '<div class="flow-step '+(done?'done ':'')+(active?'active':'')+'"><b>'+(done&&!active?'✓':n)+'</b><span>'+text+'</span></div>';}
function hero(){
 const r=current(),q=queued();
 if(!r){const p=paused();return '<section class="hero calm"><div class="hero-orb">✓</div><div><span class="kicker">TUDO TRANQUILO</span><h2>Nada sendo feito agora</h2><p>'+(q.length?q.length+' tarefa'+(q.length>1?'s':'')+' esperando para começar.':p.length?p.length+' tarefa'+(p.length>1?'s pausadas.':' pausada.'):'A fila está vazia.')+'</p></div></section>';}
 const p=taskProgress(r),a=taskActivity(r,Date.now(),state.connection),n=pct(r);
 return '<section class="hero live" data-running-id="'+e(r.id)+'"><div class="hero-top"><div><span class="live-pill"><i></i> AO VIVO</span><span class="tiny">atualizado há '+e(ago(r.last_progress_at||r.updated_at))+'</span></div><span class="score">⚡ '+n+'%</span></div><div class="hero-copy"><span class="kicker">FAZENDO AGORA</span><h2>'+e(label(r))+'</h2><p>'+e(r.progress_message||p.label||'Trabalhando nesta tarefa.')+'</p></div><div class="mega-progress"><progress aria-label="Progresso da tarefa" max="100" value="'+n+'">'+n+'%</progress><span style="--p:'+n+'%"></span></div><div class="flow">'+flowStep('1','Entrou na fila',true)+flowStep('2','Fazendo',true,true)+flowStep('3','Pronta',false)+'</div><div class="activity-bubble '+a.level+'" data-activity="'+e(r.id)+'"><span class="pulse-dot"></span><strong>'+e(a.text.replace(/^[●!◷○]\s*/,''))+'</strong><small>'+e(a.since)+'</small></div><button class="ghost action" data-task="'+e(r.id)+'">Ver um pouco mais</button></section>';
}
function snapshot(){const s=stats(),q=queued(),p=paused();return '<section class="snapshot"><article><span>▶</span><strong>'+(current()?1:0)+'</strong><small>fazendo agora</small></article><article><span>◷</span><strong>'+(q.length+p.length)+'</strong><small>pendentes</small></article><article><span>✓</span><strong>'+(s.counts.succeeded||0)+'</strong><small>prontas</small></article><article><span>✦</span><strong>'+Math.round(s.completionRate||0)+'%</strong><small>de sucesso</small></article></section>';}
function nextUp(){const q=pending().slice(0,4);return '<section class="card"><div class="section-title"><div><span class="kicker">DEPOIS</span><h3>Pendências</h3></div><span class="count">'+pending().length+'</span></div>'+(q.length?'<div class="queue">'+q.map((r,i)=>'<button data-task="'+e(r.id)+'"><b>'+(i+1)+'</b><span>'+e(label(r))+'<small>'+(r.status==='paused'?'pausada':'esperando para começar')+'</small></span><i>›</i></button>').join('')+'</div>':'<div class="empty-state">Sem tarefas pendentes 🎉</div>')+'</section>';}
function wins(){const rows=done().slice(0,5);return '<section class="card"><div class="section-title"><div><span class="kicker">ÚLTIMAS ENTREGAS</span><h3>O que já ficou pronto</h3></div></div><div class="wins-list">'+(rows.length?rows.map(r=>'<button class="'+(r.status==='failed'?'failed':'')+'" data-task="'+e(r.id)+'"><span class="result-dot '+e(r.status)+'"></span><span>'+e(label(r))+'<small>'+e(copy[r.status]||statusLabel(r.status))+' · '+date(r.completed_at||r.updated_at)+'</small></span><i>'+(r.status==='succeeded'?'✓':'⚠')+'</i></button>').join(''):'<div class="empty-state">As entregas vão aparecer aqui.</div>')+'</div></section>';}
function overview(){return '<div class="overview">'+hero()+snapshot()+'<div class="split">'+nextUp()+wins()+'</div></div>';}
function livePage(){
 const r=current(),events=r?state.live.filter(x=>x.id===r.id).slice(-120):[],n=r?pct(r):0;
 const stage=events.filter(x=>x.kind==='stage').at(-1)?.message||r?.progress_message||'Executando';
 const lines=events.length?events.map(x=>'<div class="terminal-line '+e(x.kind||'output')+'"><time>'+e(new Date(x.at||Date.now()).toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit',second:'2-digit'}))+'</time><span>'+e(x.message||'')+'</span></div>').join(''):'<div class="terminal-empty">Aguardando novos eventos…</div>';
 const last=done()[0];return '<section class="live-page"><div class="live-head"><div><span class="live-pill"><i></i> TEMPO REAL</span><h2>'+(r?e(label(r)):'Nenhuma tarefa em execução')+'</h2><p>'+(r?e(r.progress_message||'Acompanhando o Termux em tempo real.'):'Quando uma tarefa começar, ela aparecerá aqui automaticamente.')+'</p></div><div class="live-percent">'+n+'%</div></div>'+(r?'<div class="live-progress"><progress aria-label="Progresso ao vivo" max="100" value="'+n+'"></progress></div><div class="live-stage-grid"><div><span>Etapa atual</span><strong>'+e(stage)+'</strong></div><div><span>Eventos</span><strong>'+events.length+' nesta sessão</strong></div><div><span>Atualização</span><strong>'+e(ago(r.last_progress_at||r.updated_at))+'</strong></div></div><section class="terminal-card"><div class="terminal-top"><div><i></i><span>Termux ao vivo</span></div><small>conteúdo sensível é ocultado</small></div><div id="live-terminal" class="live-terminal" aria-live="polite">'+lines+'</div></section>':'<div class="empty-state big">O painel está conectado e aguardando a próxima execução.'+(last?'<br><br>Última atividade: <strong>'+e(label(last))+'</strong> · '+e(copy[last.status]||statusLabel(last.status)):'')+'</div>')+'</section>';
}
function filters(history=false){const choices=history?['succeeded','failed','cancelled']:['queued','paused','running','succeeded','failed','cancelled'];return '<div class="filters"><input id="task-search" type="search" value="'+e(state.search)+'" placeholder="Buscar tarefa..."><select id="task-status"><option value="all">Todas</option>'+choices.map(x=>'<option value="'+x+'" '+(state.status===x?'selected':'')+'>'+e(copy[x])+'</option>').join('')+'</select></div>';}
function taskRows(history=false){const sourceRows=!history&&state.page.rows?state.page.rows:state.rows;const rows=!history&&state.page.rows?sourceRows:filterTasks(sourceRows,{search:state.search,status:state.status,terminal:history});return rows.length?'<div class="task-grid">'+rows.map(r=>'<button class="task-card '+e(r.status)+'" data-task="'+e(r.id)+'"><div class="task-card-top"><span class="task-state">'+(r.status==='failed'?'⚠ ':'')+e(copy[r.status]||statusLabel(r.status))+'</span><span class="task-percent">'+e(pctText(r))+'</span></div><strong>'+e(label(r))+'</strong><div class="mini-bar"><i style="width:'+pct(r)+'%"></i></div><small>'+(r.status==='running'?e(r.progress_message||'em andamento'):date(r.completed_at||r.created_at))+'</small></button>').join('')+'</div>':'<div class="empty-state big">Nada por aqui.</div>';}
function pager(){if(state.mode!=='live')return '';return '<div class="pager"><button id="page-prev" '+(state.page.number<=1||state.page.loading?'disabled':'')+'>← Anterior</button><span>Página '+state.page.number+'</span><button id="page-next" '+(!state.page.hasNext||state.page.loading?'disabled':'')+'>Próxima →</button></div>';}
function taskPage(history=false){return '<section class="simple-page"><div class="page-intro"><span class="kicker">'+(history?'RESULTADOS':'FLUXO')+'</span><h2>'+(history?'Entregas recentes':'Todas as tarefas')+'</h2></div>'+filters(history)+'<div id="task-results">'+taskRows(history)+'</div>'+(history?'':pager())+'</section>';}
function projectsPage(){
 const cards=state.projects.length?state.projects.map(p=>'<article class="card project-card"><div class="section-title"><div><span class="kicker">PROJETO</span><h3>'+e(p.name)+'</h3></div><span class="task-state">'+e(p.github_status==='linked'?'GitHub ligado':p.github_status==='provisioning'?'Criando repositório':p.github_status==='failed'?'Falha no GitHub':'Sem GitHub')+'</span></div><p>'+e(p.description||'Sem descrição.')+'</p>'+(p.github_repo_full_name?'<small>'+e(p.github_repo_full_name)+(p.github_branch?' · '+e(p.github_branch):'')+'</small>':'')+'</article>').join(''):'<div class="empty-state big">Nenhum projeto cadastrado.</div>';
 return '<section class="simple-page"><div class="page-intro"><span class="kicker">PROJETOS</span><h2>Organize as tarefas por projeto</h2><p>Toda nova tarefa precisa estar ligada a um projeto.</p></div><section class="card"><h3>Novo projeto</h3><form id="project-form"><label>Nome<input name="name" required maxlength="80"></label><label>Descrição<input name="description" maxlength="240"></label><label class="project-check"><input name="createGithub" type="checkbox"> Criar também um repositório no GitHub</label><div id="github-fields" hidden><label>Nome do repositório<input name="repoName" maxlength="100" placeholder="opcional"></label><label>Visibilidade<select name="visibility"><option value="private">Privado</option><option value="public">Público</option></select></label></div><p id="project-error" role="alert"></p><button class="primary" type="submit">Criar projeto</button></form></section><div class="project-grid">'+cards+'</div></section>';
}
function settings(){const s=stats();return '<section class="simple-page"><div class="page-intro"><span class="kicker">SISTEMA</span><h2>Está tudo conectado?</h2><p>Estado atual do dashboard e dos dados carregados.</p></div><div class="system-card"><div class="system-orb '+e(state.connection)+'"></div><div><strong>'+(state.connection==='live'?'Atualização ao vivo':'Reconectando')+'</strong><small>'+(state.connection==='live'?'Novidades aparecem automaticamente.':'Tentando restabelecer a conexão automaticamente.')+'</small></div></div><section class="snapshot"><article><span>≡</span><strong>'+Number(s.total||0)+'</strong><small>tarefas 30 dias</small></article><article><span>◷</span><strong>'+paused().length+'</strong><small>pausadas visíveis</small></article><article><span>✓</span><strong>'+Number(s.counts?.succeeded||0)+'</strong><small>concluídas</small></article><article><span>!</span><strong>'+Number(s.counts?.failed||0)+'</strong><small>falhas</small></article></section><details class="advanced"><summary>Opções</summary><div class="advanced-body"><button id="pause-follow" aria-pressed="false">Pausar animações</button><input id="log-search" type="search" placeholder="Filtro visual"><p>Login fica salvo neste navegador enquanto a sessão for válida.</p></div></details></section>';}
function render(){navHtml();main.innerHTML=state.route==='overview'?overview():state.route==='live'?livePage():state.route==='tasks'?taskPage(false):state.route==='history'?taskPage(true):state.route==='projects'?projectsPage():settings();bind();$('#updated').textContent='Atualizado '+new Date().toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'});}
let searchTimer;function bind(){main.querySelectorAll('[data-task]').forEach(el=>el.onclick=()=>openDetail(el.dataset.task));const pf=$('#project-form');if(pf){const gh=pf.elements.createGithub,fields=$('#github-fields');gh.onchange=()=>fields.hidden=!gh.checked;pf.onsubmit=async ev=>{ev.preventDefault();const err=$('#project-error');err.textContent='';const fd=new FormData(pf);try{const created=await source.createProject({name:fd.get('name'),description:fd.get('description'),createGithub:fd.get('createGithub')==='on',repoName:fd.get('repoName'),visibility:fd.get('visibility')});state.projects=[created,...state.projects.filter(p=>p.id!==created.id)];render();}catch(x){err.textContent=x?.message||'Não foi possível criar o projeto.';}};}const s=$('#task-search');if(s)s.oninput=()=>{state.search=s.value;if(state.route==='tasks'){clearTimeout(searchTimer);searchTimer=setTimeout(()=>{resetPage();void loadTaskPage(1);},250);}else{$('#task-results').innerHTML=taskRows(true);bind();}};const st=$('#task-status');if(st)st.onchange=()=>{state.status=st.value;if(state.route==='tasks'){resetPage();void loadTaskPage(1);}else{$('#task-results').innerHTML=taskRows(true);bind();}};const prev=$('#page-prev');if(prev)prev.onclick=()=>void loadTaskPage(state.page.number-1);const next=$('#page-next');if(next)next.onclick=()=>void loadTaskPage(state.page.number+1);const p=$('#pause-follow');if(p)p.onclick=()=>{const v=p.getAttribute('aria-pressed')==='true';p.setAttribute('aria-pressed',String(!v));document.body.classList.toggle('paused',!v);};}
function resetPage(){state.page={number:1,rows:null,cursors:[null],hasNext:false,loading:false};}
async function loadTaskPage(number=1){if(!source||state.mode!=='live'||number<1)return;const cursor=state.page.cursors[number-1];if(number>1&&!cursor)return;state.page.loading=true;render();try{const rows=await source.list(queuePageArgs({status:state.status,search:state.search,cursor,limit:12}));const page=queuePageResult((rows||[]).map(normalize),12);state.page.number=number;state.page.rows=page.rows;state.page.hasNext=page.hasNext;if(page.nextCursor)state.page.cursors[number]=page.nextCursor;state.page.loading=false;render();}catch{state.page.loading=false;render();}}
function renderBuild(){const el=$('#build-status');if(!el)return;const b=state.build;if(b.status==='hidden'||(b.status==='success'&&Date.now()>b.visibleUntil)){el.hidden=true;return;}el.hidden=false;el.className='build-status '+b.status;el.innerHTML=b.status==='running'?'<i></i> Atualizando':b.status==='success'?'✓ Concluído':'⚠ Falha no build';}
async function refreshBuildStatus(){try{const response=await fetch('https://api.github.com/repos/AmaroPSJunior/codex-bridge-queue/actions/runs?per_page=30',{cache:'no-store',headers:{Accept:'application/vnd.github+json'}});if(!response.ok)return;const body=await response.json(),next=buildReleaseState(body.workflow_runs||[]),changed=state.build.sha!==next.sha||state.build.status!==next.status;state.build.sha=next.sha;state.build.status=next.status;if(changed&&next.status==='success')state.build.visibleUntil=Date.now()+8000;renderBuild();}catch{}}
async function openDetail(id){let r=state.rows.find(x=>x.id===id)||state.page.rows?.find(x=>x.id===id);if(state.mode==='live'&&source){try{r=normalize(await source.detail(id)||r);}catch{}}if(!r)return;const canDelete=canDeleteTask(r,state.mode),failure=r.status==='failed'?'<section class="failure-reason"><span>⚠ Motivo da falha</span><p>'+e(r.error_summary||r.error||'Motivo não informado')+'</p></section>':'';$('#detail-body').innerHTML='<span class="kicker">'+e(copy[r.status]||statusLabel(r.status))+'</span><h2 id="detail-title">'+e(label(r))+'</h2><div class="detail-progress"><progress aria-label="Progresso detalhado" max="100" value="'+pct(r)+'"></progress><strong>'+e(pctText(r))+'</strong></div><p class="detail-message">'+e(r.progress_message||'Sem mensagem nova.')+'</p>'+failure+'<div class="detail-facts"><div><span>Começou</span><strong>'+date(r.claimed_at||r.created_at)+'</strong></div><div><span>Tempo</span><strong>'+duration(seconds(r.claimed_at,r.completed_at||new Date().toISOString()))+'</strong></div></div><div class="detail-actions"><button id="delete-task" class="danger" '+(canDelete?'':'disabled')+'>'+((r.status==='running')?'Não é possível excluir em execução':'Excluir tarefa')+'</button></div>';const del=$('#delete-task');if(del&&canDelete)del.onclick=()=>deleteTask(r);$('#detail-dialog').showModal();}
async function deleteTask(r){if(!source||!confirmTaskDeletion(confirm,r,state.mode,label))return;const button=$('#delete-task');if(button){button.disabled=true;button.textContent='Excluindo…';}try{const removed=await source.deleteTask(r.id);if(!removed)throw Error('Tarefa não encontrada.');state.rows=removeTaskRows(state.rows,r.id);if(state.page.rows)state.page.rows=removeTaskRows(state.page.rows,r.id);$('#detail-dialog').close();await refresh();}catch(err){if(button){button.disabled=false;button.textContent='Excluir tarefa';}alert(err?.message||'Não foi possível excluir a tarefa.');}}
async function refreshRoute(){
 if(!source||state.mode!=='live')return refresh();
 try{
  if(state.route==='tasks'){resetPage();await loadTaskPage(1);return;}
  const requests=[source.list({p_limit:50}),source.stats(),source.projects?source.projects():Promise.resolve([])];
  const [rows,summary,projects]=await Promise.all(requests);
  state.rows=(rows||[]).map(normalize);state.stats=summary;state.projects=projects||[];
  if(state.route==='history'&&!['all','succeeded','failed','cancelled'].includes(state.status))state.status='all';
  render();
 }catch{state.connection='offline';render();}
}
async function refresh(){if(!source)return;try{if(state.mode==='public')state.stats=await source.stats();else if(state.mode==='live'){const rows=await source.list({p_limit:50});state.rows=(rows||[]).map(normalize);state.stats=await source.stats();if(state.route==='tasks'){resetPage();await loadTaskPage(1);return;}}render();}catch{state.connection='offline';render();}}
async function event(payload){
 if(!payload?.id||!source||state.mode!=='live')return;
 const operation=String(payload.operation||'').toUpperCase();
 let fresh=payload.task||null;
 if(operation!=='DELETE'&&!fresh){try{fresh=await source.summary(payload.id);}catch{}}
 state.rows=applyTaskChange(state.rows,payload,fresh?normalize(fresh):null);
 if(state.page.rows)state.page.rows=applyTaskChange(state.page.rows,payload,fresh?normalize(fresh):null);
 try{state.stats=await source.stats();}catch{}
 if(state.route==='tasks'){
  if(operation==='INSERT'){resetPage();await loadTaskPage(1);return;}
  const target=Math.max(1,state.page.number||1);await loadTaskPage(target);return;
 }
 render();
}
function liveEvent(payload){if(!payload||typeof payload!=='object'||!payload.id)return;state.live.push(payload);if(state.live.length>500)state.live.splice(0,state.live.length-500);const row=state.rows.find(x=>x.id===payload.id);if(row&&typeof payload.percent==='number')row.progress_percent=payload.percent;if(state.route==='live'){render();requestAnimationFrame(()=>{const box=$('#live-terminal');if(box)box.scrollTop=box.scrollHeight;});}}
async function boot(){render();let config={};try{config=await fetch('./public-config.json',{cache:'no-store'}).then(r=>r.ok?r.json():({}));}catch{}if(config.publicSummaryPath){state.rows=[];state.mode='public';source=createPublicData({config,onRefresh:refresh,onState:s=>{state.connection=s;render();}});state.stats=await source.stats();await source.subscribe();state.connection='live';render();return;}if(config.publishableKey){state.rows=[];try{source=await createData(config,{onEvent:event,onLive:liveEvent,onState:s=>{state.connection=s;render();},onRefresh:refresh,onAuthLost:()=>$('#login-dialog').showModal()});if(await source.restore()){state.mode='live';try{state.projects=await source.projects();}catch{}await refresh();await source.subscribe();state.connection='live';$('#notice').hidden=true;render();return;}state.mode='live';$('#login-dialog').showModal();}catch{$('#login-dialog').showModal();}}else{state.rows=[];state.stats=null;state.mode='offline';state.connection='offline';$('#notice').hidden=true;render();}}
window.addEventListener('hashchange',()=>{state.route=location.hash.slice(1) in routes?location.hash.slice(1):'overview';if(state.route==='history'&&!['all','succeeded','failed','cancelled'].includes(state.status))state.status='all';render();void refreshRoute();});
$('#refresh').onclick=refresh;
$('#login-form').onsubmit=async ev=>{ev.preventDefault();const fd=new FormData(ev.currentTarget),err=$('#login-error');err.textContent='';try{await source.login(fd.get('email'),fd.get('password'));$('#login-dialog').close();try{state.projects=await source.projects();}catch{}await refresh();await source.subscribe();state.connection='live';$('#notice').hidden=true;}catch(x){err.textContent=x.message;}};
document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>b.closest('dialog').close());
state.route=location.hash.slice(1) in routes?location.hash.slice(1):'overview';
boot();
void refreshBuildStatus();setInterval(refreshBuildStatus,15000);setInterval(()=>{if(state.route==='overview')render();renderBuild();},30000);setInterval(()=>{if(state.route==='projects'&&source&&state.mode==='live')void source.projects().then(p=>{state.projects=p||[];render();}).catch(()=>{});},3000);
